- type: job
  id: Blueshield
  name: blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueshield
  requireAdminNotify: true
  joinNotifyCrew: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 #50 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000 #50 hrs
    - !type:OverallPlaytimeRequirement
      time: 180000 #50 hrs
  startingGear: BlueshieldGear
  icon: "JobIconBlueShield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  setPreference: true
  access:
  - BlueShield
  - Maintenance
  - Command
  - Service
  - External
  - Brig
  - Security
  - Medical
  - Chemistry
  - CentralCommand
  - CCSecurity
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Command
  wage: 80
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueShield
    head: ClothingHeadBeretBlueShield
    back: ClothingBackpackBlueshieldFilled
    belt: ClothingBeltBlueshieldWebbinFilled
    shoes: ClothingShoesBlueShieldShoes
    eyes: ClothingEyesGlassesSunglassesMed
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterBlueShieldVest
    suitstorage: WeaponSubMachineGunDrozd
    id: BlueShieldPDA
    ears: ClothingHeadsetAltCentCom
    mask: ClothingMaskGasSecurity
    pocket1: RubberStampBlueshield
  storage:
    back:
    - BoxSurvivalEngineering
    - Flash
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGunRubber
 # innerClothingSkirt: ClothingUniformJumpskirtBlueShield
 # satchel: ClothingBackpackBlueshieldFilled # blueshield didnt need duffels and satchels
 # duffelbag: ClothingBackpackBlueshieldFilled
